---
title: "Machine Learning Project"
author: "Jeremy T. Finke"
date: "August 22, 2015"
output: html_document
---

# Executve Overview

The purpose of this project is to develop a machine learning model to acurately predict the outcome of a dataset. The dataset in question is data from an experiment for Human Activity Recognition (HAR). The experiment is outlined at:  http://groupware.les.inf.puc-rio.br/har  

The experiment utilized six particpants outfitted with accelerometers to perform lightweight dumbell curls with five different methods (classes). The goal of this project was to determine what the method was for the activity.  The model developed had an accuracy rating of 99.1% with a full 20/20 correct for the related submission.

# Data Loading
The data was manually downloaded from: https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv in order to have a local copy and put into the repository.

It was then loaded in by:
```{r}
pml.training <- read.csv("~/machinelearning/pml-training.csv")
```

# Data Cleaning


# Data Modeling


# Conclusion